---
title: "Study on BCF Versus Other Methods"
output: pdf_document
date: "2025-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(horseshoe)
```

```{r}
simulate_once = function(n, tau_type, mu_type, sigma) {
  x1 = rnorm(n, 0, 1)
  x2 = rnorm(n, 0, 1)
  x3 = rnorm(n, 0, 1)
  x4 = rbinom(n, 1, 0.5)
  x5 = sample(1:3, n, replace = TRUE)
  g = 5 - 3 * x5
  u = runif(n, 0, 1)
  
  # tau
  if (tau_type == "homogeneous") {
    tau_true = 3
  } else if (tau_type == "heterogeneous") {
    tau_true = 1 + 2 * x2 * x4 # subject to change
  } else {
    stop("tau_type can only be 'homogeneous' or 'heterogeneous'.")
  }
  
  # mu
  if (mu_type == "linear") {
    mu_true = 1 + g + x1 * x3
  } else if (mu_type == "nonlinear") {
    mu_true = -6 + g + 6 * abs(x3 - 1)
  } else {
    stop("mu_type can only be 'linear' or 'nonlinear'.")
  }
  
  s = sd(mu_true)
  
  # pi
  pi = 0.8 * pnorm(3*mu_true/s-x1/2, 0, 1) + 0.05 + u / 10
  
  z = rbinom(n, 1, pi)
  err = rnorm(n, 0, sigma)
  y = mu_true + tau_true * z + err
  X = cbind(x1, x2, x3, x4, x5)
  X_full = cbind(X, X * z)

  hs_fit = horseshoe(y, X_full, method.tau = "truncatedCauchy", method.sigma = "Jeffreys", nmc = 1000)
  beta_samples = hs_fit$BetaSamples

  p = ncol(X)
  theta_samples = beta_samples[(p + 1):(2 * p),]

  tau_draws = X %*% theta_samples
  
  # posterior draws for ATE: column means of tau_draws
  ate_draws = colMeans(tau_draws)     # vector of length m
  ate_hat   = mean(ate_draws)         # posterior mean (point estimate)
  ate_sd    = sd(ate_draws)           # posterior std
  ate_ci    = quantile(ate_draws, probs = c(0.025, 0.975))  # credible interval
  ate_true  = mean(tau_true)          # known truth (because tau is known for all units)

  # performance metrics for ATE
  ate_rmse = abs(ate_hat - ate_true)
  ate_coverage = as.numeric(ate_true >= ate_ci[1] & ate_true <= ate_ci[2])
  ate_intlength = unname(diff(ate_ci)) 

  # posterior summary: individual treatment effect
  tau_hat = rowMeans(tau_draws)
  tau_sd  = apply(tau_draws, 1, sd)
  lower   = apply(tau_draws, 1, quantile, probs = 0.025)
  upper   = apply(tau_draws, 1, quantile, probs = 0.975)

  # evaluation metrics
  cate_rmse = sqrt(mean((tau_hat - tau_true)^2))
  cate_coverage = mean(tau_true >= lower & tau_true <= upper)
  cate_avg_len = mean(upper - lower)

  # per-variable treatment heterogeneity effects (gamma_j)
  gamma_mean = rowMeans(theta_samples)
  gamma_ci = t(apply(theta_samples, 1, quantile, probs = c(0.025, 0.975)))
  gamma_sig = !(gamma_ci[,1] < 0 & gamma_ci[,2] > 0)  # CI does not include 0

  # Create result vector with original metrics
  res = c(
    cate_rmse = cate_rmse,
    cate_coverage = cate_coverage,
    cate_interval_length = cate_avg_len,
    ate_rmse = ate_rmse,
    ate_coverage = ate_coverage,
    ate_interval_length = ate_intlength
  )

  # Add gamma summaries for each variable
  for (j in 1:length(gamma_mean)) {
    res[paste0("gamma", j, "_sig")] = as.integer(gamma_sig[j])
  }

  return(res)
}
```

```{r}
run_simulations <- function(n_rep, n, tau_type, mu_type, sigma, filename) {
  set.seed(2020)
  
  results <- replicate(n_rep,
                       simulate_once(n, tau_type, mu_type, sigma),
                       simplify = "matrix")
  
  results_df <- as.data.frame(t(results))
  # rownames(results_df) <- paste0("Sim", 1:n_rep)
  
  write.csv(results_df, file = filename, row.names = FALSE)
}
```

```{r}
n_rep = 50
sizes = c(250, 500)
tau_types = c("homogeneous", "heterogeneous")
mu_types = c("linear", "nonlinear")
sigma = 1.0
for (n in sizes) {
  for (tau_type in tau_types) {
    for (mu_type in mu_types) {
      filename = paste0("results/horseshoe_", mu_type, "_", tau_type, "_", n, ".csv")
      results = run_simulations(n_rep, n, tau_type, mu_type, sigma, filename)
    }
  }
}
```

```{r}
for (n in sizes) {
  for (tau_type in tau_types) {
    for (mu_type in mu_types) {
      filename = paste0("results/horseshoe_", mu_type, "_", tau_type, "_", n, ".csv")
      results = read.csv(filename)
      gamma_sig = colMeans(results[,7:11])
      print(filename)
      print(gamma_sig)
    }
  }
}
```